### ISSUE TITLE
Cannot find module 'casper'

### ISSUE THREAD

**Issue by IPconfig** [sebastienvercammen/nintendo-ptc-account-generator#1]
After following the instructions to start this project, I get the following output:
```
> node index.js

module.js:442
    throw err;
    ^

Error: Cannot find module 'casper'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/justin/Downloads/nintendo-ptc-account-generator-master/index.js:2:14)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.3.1/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! nintendo-ptc-account-generator@1.0.0 start: `node index.js`
npm ERR! Exit status 1
```

It seems it misses the path to caspjerjs or something (I'm a total noob with Node.js in general)

**Comment by sebastienvercammen** [comment]
Hi Justin,

 

You’re correct, I still need to update the installation instructions, but I’m first working on a slightly modified version which allows random passwords and a list of usernames.

 

To install:

*         Manually install phantomjs and add it to your OS’ path

*         Do the same for casperjs

*         Run the project with “casperjs index.js”

 

Hope it helps,

 

Seb

**Comment by sebastienvercammen** [comment]
Hi Justin,

You’re correct, I still need to update the installation instructions, but I’m first working on a slightly modified version which allows random passwords and a list of usernames.

To install:
* Manually install phantomjs and add it to your OS’ path environment variable
* Do the same for casperjs
* Run the project with "casperjs index.js"

I'll commit the changes later tonight and update the installation instructions.

**Comment by sebastienvercammen** [comment]
Solved in the latest commit. Enjoy.
