### ISSUE TITLE
Retrying when second or first page "Maintenance"

### ISSUE THREAD

**Issue by maxmustermann6426** [sebastienvercammen/nintendo-ptc-account-generator#10]
Please fix this. Thanks.

```
[0] First Page: The Official Pokémon Website | Pokemon.com
[0] Second Page: The Official Pokémon Website | Pokemon.com
Finished 0.
[1] First Page: The Official Pokémon Website | Pokemon.com
[1] Server is acting up. Retrying...
[1] First Page: The Official Pokémon Website | Pokemon.com
[1] Second Page: Maintenance | The Official Pokémon Website | Pokemon.com
Err: CasperError: Errors encountered while filling form: form not found
```

**Comment by sebastienvercammen** [comment]
@maxmustermann6426 Fixing this will be kind of hard, considering the problem is that Nintendo's website is under maintenance as shown in:

`[1] Second Page: Maintenance | The Official Pokémon Website | Pokemon.com`

**Comment by maxmustermann6426** [comment]
You can do a simple retry / loop, when the "First Page" in maintenance. When the "Second Page", begin at "First Page" and not save the credentials in "accounts.txt", when not successfully.

**Comment by sebastienvercammen** [comment]
@maxmustermann6426 This is true, and I can fix this, but this is not urgent and would also increase the load on Nintendo's servers **when they are already not properly working** (e.g. maintenance, server crash).

I'm also busy with http://www.pokespawns.be so this is a low priority. It's open source though, so you're always welcome to contribute with a pull request.
