### ISSUE TITLE
Form Not Found Error

### ISSUE THREAD

**Issue by ph3l1x** [sebastienvercammen/nintendo-ptc-account-generator#11]
[o] Starting 0 to 9.
[0] First Page: Maintenance | The Official Pokémon Website | Pokemon.com
Err: CasperError: Errors encountered while filling form: form not found

Does this repo no longer work?

**Comment by sebastienvercammen** [comment]
@ph3l1x It does work. Nintendo's webpage is just down for Maintenance, like it says in the page title:

```
First Page: Maintenance
``` 

I'm also working on a new version w/ less requirements that handles downtime/errors much better. So stay tuned.
