### ISSUE TITLE
Form not found 

### ISSUE THREAD

**Issue by nikos90** [sebastienvercammen/nintendo-ptc-account-generator#2]
I am getting the error below when a start the script.

CasperError: Errors encountered while filling form: form not found              
  /Applications/MAMP/htdocs/nintendo-ptc-account-generator:706 in fill
  /Applications/MAMP/htdocs/nintendo-ptc-account-generator/index.js:51
  /Applications/MAMP/htdocs/nintendo-ptc-account-generator:1335 in runStep
  /Applications/MAMP/htdocs/nintendo-ptc-account-generator:332 in checkStep
Err: CasperError: Errors encountered while filling form: form not found

**Comment by sebastienvercammen** [comment]
@nikos90 This happens when Nintendo has temporarily disabled registrations due to heavy load. You will notice the page title displayed in the console will mention "Maintenance".

Manually visit their website and try again when it's online. Let me know if it worked.

**Comment by nikos90** [comment]
@sebastienvercammen i can sign up manually.
The weird thing is that i can't even see the title. 
It is blank.

o] Starting 0 to 9.
[0] First Page:

**Comment by sebastienvercammen** [comment]
@nikos90 Can you give me the output of the following commands?

`node -v`
`phantomjs -v`
`casperjs --version`

I've also just pushed a version that includes `verbose: false` (line #3). Set it to `verbose: true` and run the script again. Paste the output on here.

**PS:** as a tip, in the comment editor on GitHub there's an "Insert code" button that looks like **<>**. Use it to paste code or terminal output.

**Comment by nikos90** [comment]
`node -v = v0.12.2`
`phantomjs -v = 2.1.1`
`casperjs --version = 1.0.4`


`[info] [phantom] Starting...`
 `[o] Starting 0 to 9.`
`[info] [phantom] Running suite: 40 steps`
`[debug] [phantom] opening url: https://club.pokemon.com/us/pokemon-trainer-club/sign-up/, HTTP GET`
`[debug] [phantom] Navigation requested: url=https://club.pokemon.com/us/pokemon-trainer-club/sign-up/, type=Other, lock=true, isMainFrame=true`
`[warning] [phantom] Loading resource failed with status=fail: https://club.pokemon.com/us/pokemon-trainer-club/sign-up/`
`[debug] [phantom] Successfully injected Casper client-side utilities`
`[0] First Page: `
`[info] [remote] attempting to fetch form element from selector: 'form[name="verify-age"]'`
`CasperError: Errors encountered while filling form: form not found              `
 ` /Applications/MAMP/htdocs/nintendo-ptc-account-generator:706 in fill`
 ` /Applications/MAMP/htdocs/nintendo-ptc-account-generator/index.js:54`
 ` /Applications/MAMP/htdocs/nintendo-ptc-account-generator:1335 in runStep`
  `/Applications/MAMP/htdocs/nintendo-ptc-account-generator:332 in checkStep`
`Err: CasperError: Errors encountered while filling form: form not found`

**Comment by sebastienvercammen** [comment]
Your node and casperjs are outdated.

Current versions are:
* [Node.js 6.3.1](https://nodejs.org/en/) (get current, not LTS)
* [CasperJS 1.1.3](http://casperjs.org/)

Update, try again, and let me know how it went.

**Comment by nikos90** [comment]
It worked thanks!!

**Comment by sebastienvercammen** [comment]
Glad to hear it helped :) Enjoy.
