### ISSUE TITLE
Problem after running the script

### ISSUE THREAD

**Issue by nikos90** [sebastienvercammen/nintendo-ptc-account-generator#3]
Ok that's weird.
I git clone the project, run the script, everything works perfectly and the accounts are created.
I then retry to run the script, but nothing is happening.
i don't even get debug messages while the debugger is active.
Any ideas?

**Comment by sebastienvercammen** [comment]
@nikos90 Sounds like you have a typo (e.g. missing comma) in your nicknames list.

**Comment by nikos90** [comment]
@sebastienvercammen the mac's notepad was replacing " character with invalid.
Damn!
Thanks
