### ISSUE TITLE
Script runs, no accounts are created

### ISSUE THREAD

**Issue by MDausch** [sebastienvercammen/nintendo-ptc-account-generator#4]
The script seems to run fine, yet after it finishes I go to the email account I used and there are no confirmation emails, nor are the accounts actually created when checked on the ptc sign in.

I see you list that it needs phantoms 2.1.7+ to run yet the highest version I am able to find is 2.1.1, so that might be the problem.If you could toss the link to that I would appreciate it. Thanks

**Comment by sebastienvercammen** [comment]
@MDausch 2.1.7+ was a typo on my behalf, good catch. I've fixed it.

If you get output (e.g. First Page, Second Page, Finished), then the script is running fine. Could you give me more info on what e-mail host you are using and whether PTC was having server issues at the time of account creation?

Today _has_ been a hectic day for PTC servers, and I recommend Gmail for the e-mails (and if it's a brand new Gmail account, wait at least 30 minutes and send yourself a test mail from another account first to confirm it's active).

Thanks.

**Comment by MDausch** [comment]
@sebastienvercammen Im using gmail. The ptc servers allowed me to make accounts manually just fine.

**Comment by MDausch** [comment]
@sebastienvercammen It seems it needed to have verbose logging set to true. It works now for me.
