### ISSUE TITLE
Loading resource failed

### ISSUE THREAD

**Issue by Precission** [sebastienvercammen/nintendo-ptc-account-generator#6]
![image](https://cloud.githubusercontent.com/assets/10085827/17327097/fbd9af2a-58b5-11e6-9059-85e47eafd701.png)

I get this error when I try to run the script. Seems like it is not finding the web page?

**Comment by sebastienvercammen** [comment]
@Precission Can you give me the output of the following?

```
node -v
phantomjs -v
casperjs --version
```

**Comment by Precission** [comment]
casperjs --version 
1.1.3

nodejs -v
v6.3.1

phantomjs -v
1.9.1

**Comment by sebastienvercammen** [comment]
Could you update your PhantomJS to 2.1.1+? I haven't tested it with lower version.

**Comment by Precission** [comment]
2.1.1 solved the issue

Thank you. When I tried to run the script with casperjs and had phantomjs 1.8.0, it asked for the minimum version of 1.9.1 so I just installed that without checking the latest build.
