### ISSUE TITLE
Error messages after editting settings in index

### ISSUE THREAD

**Issue by Stiltjes55** [sebastienvercammen/nintendo-ptc-account-generator#7]
I am trying to make some accounts but I get this error message when I edit anything past `var country` in the index file.

Example of error :
`SyntaxError: Invalid character '\u8216'

  phantomjs://code/index.js:21 in injectJs
  phantomjs://code/bootstrap.js:435` 

Is it my environment?  When I put everything back to its original form it works, but I make one change to the username, email_user or email_domain and I get the error above.  Thanks in advance!

**Comment by sebastienvercammen** [comment]
@Stiltjes55 Can you post a paste/screenshot of your settings? It most likely contains an invalid character.

**Comment by Stiltjes55** [comment]
`// Settings
var start = 0; // Start from x (NAMEx, EMAIL+x@domain.com)
var end = 10;  // Up to x, but not including (exclusive)

var useNicknamesFile = false;        // Use nicknames file, or just append numbers to username?
var useRandomPassword = false;       // Generate a random password?

var outputFile = 'accounts.txt';        // File which will contain the generated "username password" combinations.
var outputFormat = '%NICK% %PASS%\r\n'; // Format used to save the account data in outputFile. Supports %NICK%, %PASS%.

var country = 'US';                 // Country code (BE, NL, FR, ...)
var dob = '1990-12-30';             // Date of birth, YYYY-mm-dd
var username =‘tricougcitys’;              // User- & display name. Make sure any "(username + number)@domain.com" is 100% unique.
var password =‘Collins36’;              // Static password for all accounts. Ignored if useRandomPassword is true.
var email_user =’stilts5529’;           // If your email is email@domain.com, enter "email"
var email_domain = ‘gmail.com';    // Domain of e-mail host`

**Comment by Stiltjes55** [comment]
Thank you

**Comment by sebastienvercammen** [comment]
@Stiltjes55 Your editor or OS has automatically changed all single quotes `'` to special characters `‘`. Use an editor that does not do this, and everything will work perfectly.
